project:
  type: book
  output-dir: docs

book:
  title: "MLE 2023"
  date: "September 2023"
  chapters:
    - index.qmd
    - 02-ROverview.qmd
    - 03-TheMATH.qmd
    - 04-ReviewofOLS.qmd
    - 05-IntrotoMaximumLikelihood.qmd
    - 06-BinaryOutcomes.qmd
    - 07-QuantitiesofInterest.qmd
    - 08-OrdinalandOutcomes.qmd
    - 09-NominalOutcomes.qmd
    - 10-CountData.qmd
    - 11-SampleSelection.qmd
  page-navigation: true
  sidebar:
    style: docked
    background: light
    foreground: darkred

format:
  html:
    theme: yeti
    toc-title: Section Contents
    toc: true
    toc-location: left
    toc-depth: 4
    linkcolor: red
    hypothesis: true

  


editor: visual
